language: objective-c
before_install:
    - brew update
    - brew install xctool
    - gem install cocoapods-keys
    - pod keys set "Chain" "a" BitStore
    - pod keys set "Analytics" "a" BitStore
    - pod install
script: xctool -workspace BitStore.xcworkspace -scheme Test -sdk iphonesimulator8.1
script: xctool -workspace BitStore.xcworkspace -scheme BitStore -sdk iphonesimulator8.1