platform :ios, '7.0'
inhibit_all_warnings!
link_with 'BitStore', 'BitStore Tests'
pod 'CoreBitcoin', :podspec => 'https://raw.github.com/oleganza/CoreBitcoin/master/CoreBitcoin.podspec'
pod 'FXBlurView'
pod 'iRate'
pod 'MBProgressHUD'
pod 'NSDate+TimeAgo'
pod 'Stripe'
pod 'PiwikTracker'